import './styles/index.scss';
import './styles/constants.scss';

import Bottombar from "./components/bottombar/bottombar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
        <Bottombar/>
      </body>
    </html>
  );
}
